config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users
  resources :profiles
  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :profile

  validates :nickname, format: { with: /\A[a-zA-Z]+\z/,
    		message: "only allows letters" }
validates :nickname, :age, :avatar, presence: true
validates :age, inclusion: { in: 18..65,
    message: "%{value} is not a valid age" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!
  def new
  	@profile = Profile.new
  end
  def create
  	@profile = current_user.build_profile(profile_params)
  	if @profile.save
  		redirect_to profile_path(@profile.id)
  	else
  		render 'new'
  	end
  end

  def show
  	@profile = Profile.find_by(id:params[:id])
  end

  def edit
  	
  end
  def update
  	
  end
  def destroy
  	
  end
 private
   def profile_params
     params.require(:profile).permit(:nickname, :age, :avatar)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

<%= link_to "login", new_user_session_path %> |
<%= link_to "logout", destroy_user_session_path, method: :delete %> |
<%= link_to "profile", profile_path(:id) %>

app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>

<%= form_for :profile, url: profiles_path do |f| %>

<% if @profile.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
 
    <ul>
    <% @profile.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<br>
  nickname: <%= f.text_field :nickname %><br />
  age : <%= f.text_field :age %><br />
   <%= f.file_field :avatar %> <br>
  <%= f.submit %>
<% end %>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>


<%= link_to "create profile", new_profile_path %>
<hr>
<%= profile.nickname %>
<%= profile.age %>
<%= image_tag @profile.avatar.url %> 